### ISSUE TITLE
1-2 Solutions and hints

### ISSUE THREAD

**Issue by soniamitchell** [IBAHCM/RPiR#11]
If you want to provide a solution button, remove the hint.
If you want to hide a solution button, add a hint.

I've tried to include exercise checking in all exercises. They don't have a solution button because I've added an empty hint.
Empty hints need filling in.

**Comment by soniamitchell** [comment]
Likewise with practical 1-4

**Comment by soniamitchell** [comment]
For exercises that aren't checked.. it might be worth providing a copy of the expected output so that students can check they've done the right thing.

**Comment by richardreeve** [comment]
This isn't necessary actually - there's an option to remove solutions from the code.

```R
tutorial_options(exercise.reveal_solution = FALSE)
```
