### ISSUE TITLE
Add GITHUB_PAT instructions

### ISSUE THREAD

**Issue by richardreeve** [IBAHCM/RPiR#128]
We should add the instructions for adding the PAT token to the end of the github instructions. I think it's just:

```R
usethis::create_github_token()
gitcreds::gitcreds_set()
```

but we need to try it on a computer where it's not already configured.

**Comment by soniamitchell** [comment]
So... Gavin doesn't have .Renviron, so I tried `gitcreds::gitcreds_set()`, without any arguments. It says Enter password or token, so I entered a PAT and it says:
```
-> Adding new credentials...
-> Removing credentials from cache...
-> Done.
```
but doesn't seem to create an .Renviron file. From the help, it seems to be some kind of PAT manager? Like a keychain for PATs? 

I know my way was a bit more complicated, but I'm uncertain what `gitcreds_set()` is supposed to do...

**Comment by richardreeve** [comment]
Well, if he then tries to install RPiR does it say it is using the PAT token when it downloads it?

**Comment by soniamitchell** [comment]
`usethis::set_github_pat()` seems to be the right function, but again.. it's not populating `.Renviron`...

**Comment by soniamitchell** [comment]
after trying both of the methods above, `install_github()` doesn't use the PAT

**Comment by soniamitchell** [comment]
I believe my way is the only true way :p and have updated the GitHub instructions accordingly. Will push it if you're happy..

**Comment by soniamitchell** [comment]
#129
