### ISSUE TITLE
4-1 Submission - Optional tasks

### ISSUE THREAD

**Issue by soniamitchell** [IBAHCM/RPiR#18]
I'd prefer not to have these kinds of optional tasks as the students might be confused as to what constitutes their grade:

"If you’d like to write a short script demonstrating it working"

**Comment by richardreeve** [comment]
Fiar enough, I'll look at it.

**Comment by soniamitchell** [comment]
I think I've caught most of them. Though maybe I'm being too strict / pessimistic!

**Comment by richardreeve** [comment]
I think we'll just see how it goes, but in the first instance just having the minimum that we need people to do to pass is probably the right approach so no-one gets too stressed.
