### ISSUE TITLE
3-1

### ISSUE THREAD

**Issue by abaumane** [IBAHCM/RPiR#190]
I am trying to do practical 3-1 and these lines are very confusing:

> We’ve added a dependency on RPiR so you can see how to add one. 

> Add an entry in the Imports field of the DESCRIPTION file
> Add an @import in the githubusername-package file

It should be specified what kind of entry we should write. I have no idea what a dependency is, nor do I understand how you added the RPiR one (even though it says you showed me).

**Comment by soniamitchell** [comment]
Good point! Will get on that 👍

**Comment by abaumane** [comment]
Maybe a hint to look at the page linked above in the practical (where you list what files are in the working directory) would be good? By looking at that I kind of figured out how to add an entry in the Imports field.

**Comment by richardreeve** [comment]
I think this is now fixed in #197 by using functions in the `usethis` package.
