### ISSUE TITLE
Merge in ProgInR?

### ISSUE THREAD

**Issue by richardreeve** [IBAHCM/RPiR#22]
Should we just merge ProgInR into this package to make things simpler?

**Comment by soniamitchell** [comment]
Could do.. I thought the point was that {progInR} was a simple package structure for the students to play with. This package has a bit extra fluff, which might need explained in the lecture..

**Comment by richardreeve** [comment]
That makes sense. I wonder whether we should create a real dummy project though, that fills in a lot of the blanks for 2.1? And then something similar later that makes a dummy package?

**Comment by soniamitchell** [comment]
Merged it in. Will get started on the dummy project (new 2-1) today.
