### ISSUE TITLE
Cannot access other's packages

### ISSUE THREAD

**Issue by McGhee-Will** [IBAHCM/RPiR#224]
Hi @richardreeve @soniamitchell, I still cannot access the packages made by others. I downloaded them using the method we used in practical series 2 and when I try to run the demo it says:

Error in find.package(package, lib.loc, verbose = verbose) : 
  there is no package called ‘hanamayallSeries03’

Any idea on how to fix this?
Cheers.

**Comment by McGhee-Will** [comment]
I figured it out, sorry to bother you 🥇

**Comment by soniamitchell** [comment]
Awesome!

**Comment by McGhee-Will** [comment]
I said that and now it won't work again... I managed to run the demo but when I try to compile the html report it says the package doesn't exist

**Comment by soniamitchell** [comment]
Hmm... try restarting R, then try compiling the notebook. If there's an error, could you take a screenshot? 

Also, could you install using `install_github()` before running `demo()`, though `install()` works fine, we're trying to simulate installing peoples packages from GitHub without having to make clones of their repositories 👍

**Comment by soniamitchell** [comment]
Also, check to see if `library(theirpackage)` is called at the top of their script

**Comment by McGhee-Will** [comment]
When I try to use install_github() it comes up with this:

> devtools::install_github("IBAHCM/hanamayallSeries03")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`IBAHCM`) and repo name (`hanamayallSeries03`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
 
After bringing it into R using the other method, I used populate_packages to get the demo to work but the html compiling didn't work

**Comment by McGhee-Will** [comment]
and the library(theirpackage) is at the top

**Comment by soniamitchell** [comment]
hmm.. it works fine for me.. I think one of the students that stayed late had a similar problem. The solution was to try installing the package using a similar method to that used in Series 2 (as you no doubt discovered). By cloning the repository, then using `devtools::install()`. Does that work?

**Comment by McGhee-Will** [comment]
Yes! Thank you
