### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by BakariMtili** [IBAHCM/RPiR#232]
Hello @soniamitchell I am receiving this error in my R 'Error in validate_gh_pat(new_gh_pat(x)) : 
  A GitHub PAT must consist of 40 hexadecimal digits'. Please can i get some assistance?
Thanks

**Comment by soniamitchell** [comment]
Hi @BakariMtili, it seems like your PAT may have been entered incorrectly, have you tried this? https://ibahcm.github.io/RPiR/articles/pages/install_github.html#add-a-pat

**Comment by BakariMtili** [comment]
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'RPiR' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2021-02-04 18:27:55 UTC
 Thats the error I receive when i try to reinstall R

**Comment by BakariMtili** [comment]
Note has already been taken, this is what I get when i follow the instructions

**Comment by soniamitchell** [comment]
Ok, could you restart R and try following the instructions in the link again?

**Comment by BakariMtili** [comment]
I am experiencing the same thing

**Comment by soniamitchell** [comment]
Other than checking your PAT has been input correctly, I can't think of anything else without looking at it. Maybe we could fix this tomorrow?

**Comment by BakariMtili** [comment]
okay!! thank you so much

**Comment by richardreeve** [comment]
No, nothing obvious without seeing you doing it I'm afraid.

**Comment by richardreeve** [comment]
PS This really belongs in the Discussion under technical issues by the way, rather than as an issue with RPiR specifically.
