### ISSUE TITLE
Error @title Missing name

### ISSUE THREAD

**Issue by DavidAnderson102** [IBAHCM/RPiR#233]
Hi, 

I'm trying to use devtools::document() to finalise my work but I get the error

> devtools::document()
Updating DavidAndersonSeries03 documentation
Loading DavidAndersonSeries03
Writing NAMESPACE
Warning: [C:\Users\102da\OneDrive\Documents\Uni Stuff\Masters QMBCE\Semester 1\RPiR\Practicals-3\DavidAndersonSeries03\R\timestep_stochastic_birth_death.R:1] @title Missing name
Writing NAMESPACE

I'm not really sure what it means.  (I'm not even sure if its even an error)

Thanks

**Comment by richardreeve** [comment]
Hi David, it would help to raise an issue in your own GitHub repository about this and @ us (richardreeve and soniamitchell) and maybe link to it from here so we can investigate your code directly if that's okay? (because this is more of a problem with your code than RPiR)
