### ISSUE TITLE
3-3 run_simple() vs run_simulation()

### ISSUE THREAD

**Issue by soniamitchell** [IBAHCM/RPiR#27]
The exercise asks student to use run_simple() but the answer repo uses run_simulation().. I assume they do the same thing, but haven't checked.

**Comment by richardreeve** [comment]
The difference is that `run_simple()` doesn't do a lot of checking, but as a result is simple enough that they should be able to understand how it works, and we provide the code for it in the example. `run_simulation()` on the other hand does more complex stuff which is beyond their skills to understand (potentially), but can catch more problems and is a "better" solution I think.
