### ISSUE TITLE
run_simple() and run_simulation()

### ISSUE THREAD

**Issue by soniamitchell** [IBAHCM/RPiR#325]
Remove the exercises that pass functions to `run_simple()` and `run_simulation()`. 

* I very rarely pass functions to functions or use `...` to pass arguments, so I find it unlikely that they'll need to.
* If you're not familiar with these functions, they're annoying to debug. 
* If we decide to keep these functions, an explanation of how the debug argument is intended to be used might also be useful.
* If we decide to keep these functions, we could ask the students to write them themselves.
* ~~Both of these contains findGlobals(), so the missing codetools dependency caused by running findGlobals() in their function files should have been a non-issue if we'd told them that.~~

**Comment by richardreeve** [comment]
These functions now use `RPiR::assert_no_globals()` so that issue is gone.

**Comment by soniamitchell** [comment]
Cool, I’ve scored out the out of date bullet point 👍
