### ISSUE TITLE
Hi, my name is Agnes Matope. You will find my repository here: https://github.com/IBAHCM/agnesmatope_0201

### ISSUE THREAD

**Issue by maryadejoh** [IBAHCM/RPiR#422]
Hi, my name is Agnes Matope. You will find my repository here: https://github.com/IBAHCM/agnesmatope_0201 

Will be happy to hear your feedback. Many thanks!

_Originally posted by @AggieMatope in https://github.com/IBAHCM/RPiR/discussions/414#discussioncomment-1695084_

**Comment by maryadejoh** [comment]
Hi Agnes. I cannot access your repository.
Is it possible to take a look at it and get back if you need help resolving it?

**Comment by AggieMatope** [comment]
Hi Mary, I have given you access to my repository now. Please let me know if anything.

Thanks
Agnes

**Comment by maryadejoh** [comment]
I have been able to access it and there is no issue.

Cheers
